openapi: 3.0.1
info:
  title: Swagger Quotes
  description: Quote app API
  termsOfService: http://swagger.io/terms/
  contact:
    email: cbellee@microsoft.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
- url: https://quote.swagger.io/v2
- url: http://quote.swagger.io/v2
tags:
- name: quote
  description: Performs operations on Quotes
  externalDocs:
    description: Find out more
    url: http://swagger.io
paths:
  /quote:
    get:
      tags:
      - quote
      summary: Get all quotes
      description: Returns all quotes
      operationId: getQuotes
      responses:
        200:
          description: successful operation
          content:
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/quote'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/quote'
        400:
          description: No quotes found
          content: {}
        404:
          description: No quotes found
          content: {}
      security:
      - api_key: []
    post:
      tags:
      - quote
      summary: Add a new quote
      operationId: addQuote
      requestBody:
        description: Quote object that needs to be added to the store
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/quote'
          application/xml:
            schema:
              $ref: '#/components/schemas/quote'
        required: true
      responses:
        200:
          description: list the quote operations
          content:
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/quote'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/quote'
        default:
          description: generic error response
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/error'
            application/json:
              schema:
                $ref: '#/components/schemas/error'
      security:
      - quotestore_auth:
        - write:quotes
        - read:quotes
      x-codegen-request-body-name: Quote
  /quote/{quoteId}:
    get:
      tags:
      - quote
      summary: Find quote by ID
      description: Returns a single quote
      operationId: getQuoteById
      parameters:
      - name: quoteId
        in: path
        description: ID of quote to return
        required: true
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: successful operation
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/quote'
            application/json:
              schema:
                $ref: '#/components/schemas/quote'
        400:
          description: Invalid ID supplied
          content: {}
        404:
          description: Quote not found
          content: {}
      security:
      - api_key: []
    post:
      tags:
      - quote
      summary: Update an existing quote
      operationId: updateQuoteById
      parameters:
      - name: quoteId
        in: path
        description: ID of quote that needs to be updated
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        description: Quote object that needs to be added to the store
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/quote'
          application/xml:
            schema:
              $ref: '#/components/schemas/quote'
        required: true
      responses:
        400:
          description: Invalid ID supplied
          content: {}
        404:
          description: Quote not found
          content: {}
        405:
          description: Validation exception
          content: {}
      security:
      - quotestore_auth:
        - write:quotes
        - read:quotes
      x-codegen-request-body-name: body
    delete:
      tags:
      - quote
      summary: Delete a quote
      operationId: deleteQuote
      parameters:
      - name: api_key
        in: header
        schema:
          type: string
      - name: quoteId
        in: path
        description: Quote id to delete
        required: true
        schema:
          type: integer
          format: int64
      responses:
        400:
          description: Invalid ID supplied
          content: {}
        404:
          description: Quote not found
          content: {}
      security:
      - quotestore_auth:
        - write:quotes
        - read:quotes
components:
  schemas:
    Tag:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
      xml:
        name: Tag
    quote:
      required:
      - email
      - id
      type: object
      properties:
        id:
          type: integer
          format: int64
        firstname:
          type: string
          example: John
        lastname:
          type: string
          example: Doe
        street:
          type: string
          example: 18 Acacia Avenue
        suburb:
          type: string
          example: Epping
        city:
          type: string
          example: Sydney
        postcode:
          type: string
          example: "2121"
        phone:
          type: string
          example: "0404123456"
        windows:
          type: array
          example: ""
          items:
            $ref: '#/components/schemas/window'
        email:
          type: string
          example: JohnDoe@home.net
        tags:
          type: array
          xml:
            name: tag
            wrapped: true
          items:
            $ref: '#/components/schemas/Tag'
      xml:
        name: quote
    window:
      required:
      - height
      - material
      - name
      - panel
      - price
      - width
      type: object
      properties:
        name:
          type: string
          example: Lounge window A
        height:
          type: integer
          example: 1200
        width:
          type: integer
          example: 2400
        notes:
          type: string
          example: a description of the window
        price:
          type: number
          example: 560.45
        material:
          type: string
          example: wood
        panel:
          type: integer
          example: 3
    error:
      required:
      - message
      type: object
      properties:
        code:
          type: integer
          format: int64
        message:
          type: string
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
  securitySchemes:
    quotestore_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: http://quoteapp.swagger.io/oauth/dialog
          scopes:
            write:quotes: modify quotes in your account
            read:quotes: read your quotes
    api_key:
      type: apiKey
      name: api_key
      in: header
